### PR TITLE
add comment: how to set up signer from private key

### PR DESCRIPTION
**Pull request by 0xNezha**
Add comments and sample code that how to set up signer from private key, users can set singer on the testnet such as sepolia instead of the local anvil environment.

### CODE REVIEW

**Comment by yash-atreya** [comment]
Writing a private key in your code file is insecure behavior.

**Comment by 0xNezha** [comment]
> Writing a private key in your code file is insecure behavior.
Thanks!  Security is really important.  But some people do need this operation to implement some quick testing or automated procedures.   I will put risk warnings in prominent places to increase people's security awareness.

**Comment by 0xNezha** [comment]
> Writing a private key in your code file is insecure behavior.



> Writing a private key in your code file is insecure behavior.

Thanks!  Security is really important.  But some people do need this operation to implement some quick testing or automated procedures.   I will put risk warnings in prominent places to increase people's security awareness.

**Comment by 0xNezha** [comment]
> Writing a private key in your code file is insecure behavior.

Thanks! Security is really important. But some people do need this operation to implement some quick testing or automated procedures. I will put risk warnings in prominent places to increase people's security awareness.

**Pull request closed without merging**
